### PR TITLE
Fix nested folders upload

### LINKED ISSUE #89: Subfolders containing folders only are not created when uploading a folder
When uploading folder with nested folders, the structure is not recreated properly on myDrive, if a subfolder contained only other folders and no files. Subfolders containing only folders are not created at all.

Example:
Original Structure
obraz
How subfolders containing folders only were not created on myDrive:
obraz

### PR DESCRIPTION
**Pull request by FeniXb3**
Fixes #89 

I simplified code in two places as well to make it a bit easier to understand what's happening.

### CODE REVIEW

**Comment by subnub** [comment]
Hello @FeniXb3  I have quickly tested out the code and so far it seems to work fine, but I am getting 2 small typescript errors I will add comments to the lines, are you able to fix this please? Later tonight I will give a full test and merge if all is good.

Thank you! Was hoping someone could help me with this functionality as i was struggling with it.

File: backend/services/chunk-service/chunk-service.ts [hunk 1]
```diff
@@ -147,24 +153,16 @@ class StorageService {
...
-        );
-      }
+
+      const currentParent = (parentDirectory && foldersCreated[parentDirectory])
+        ? foldersCreated[parentDirectory] : rootFolder;
+
+      await fileDB.updateFolderUploadedFile(
+        currentFile.uploadedFileId,
+        user._id.toString(),
+        currentParent._id.toString(),
```
Comment (subnub) [inline backend/services/chunk-service/chunk-service.ts:163]: Here and the line below I am getting _id can possibly be null error, i think it may be okay to use `!` in this context but I would have to take a closer look later.

**Review by subnub — CHANGES_REQUESTED** [review]
Typescript fixes

File: backend/services/chunk-service/chunk-service.ts (hunk 1 above)
Comment (FeniXb3) [reply backend/services/chunk-service/chunk-service.ts]: My bad, i missed it. I fixed it and amended my comit.

**Comment by subnub** [comment]
Works great! Thanks again @FeniXb3 this was a big help, merging to master and rebuilding docker image now.
